version: 3

tasks:
  install:radar:in-cluster:
    desc: Install Radar in cluster.
    cmds:
      - helm repo add skyhook https://skyhook-io.github.io/helm-charts
      - helm upgrade --install --version 0.7.6
        --create-namespace
        --namespace radar-system radar skyhook/radar
        -f radar/helm.values.yml

  install:radar:in-local:
    desc: Install Radar in local
    cmds:
      - kubectl krew install radar
      - kubectl radar --no-browser &
