apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: eventing-hello-ping-source
spec:
  schedule: "*/2 * * * *"
  data: '{"message": "Thanks for doing Knative Tutorial"}'
  sink:  
    ref:
      apiVersion: serving.knative.dev/v1 
      kind: Service
      name: eventing-hello 