kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubernetes-stack
nodes:
- role: control-plane
  image: kindest/node:v1.29.2
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true,kourier-ready=true"
  extraPortMappings:
  # Nginx : expose port 80 (HostPort) of the node on which Nginx is deployed, to port 80 on the host (DevContainer).
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # Knative : expose port 31080 (NodePort) of all k8s nodes, to port 8080 on the host (DevContainer), later to be use by kourier.
  - containerPort: 31080
    hostPort: 8080
    protocol: TCP
  # Knative : expose port 31443 (NodePort) of all k8s nodes, to port 8443 on the host (DevContainer), later to be use by kourier.
  - containerPort: 31443
    hostPort: 8443
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  image: kindest/node:v1.29.2
- role: worker
  image: kindest/node:v1.29.2