kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubernetes-stack
nodes:
- role: control-plane
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true,kourier-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # Knative : expose port 31080 of the node to port 8080 on the host, later to be use by kourier.
  - containerPort: 31080
    hostPort: 8080
    protocol: TCP
  # Knative : expose port 31443 of the node to port 8443 on the host, later to be use by kourier.
  - containerPort: 31443
    hostPort: 8443
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
- role: worker
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245