version: 3

# Global Properties
silent: true

includes:
  ingress:
    taskfile: ./ingress/tasks.yml
    dir: ./ingress
  gitops: 
    taskfile: ./gitops/tasks.yml
    dir: ./gitops
  observability:
    taskfile: ./observability/tasks.yml
    dir: ./observability
  security:
    taskfile: ./security/tasks.yml
    dir: ./security
  platform:
    taskfile: ./platform/tasks.yml
    dir: ./platform
  serverless:
    taskfile: ./serverless/tasks.yml
    dir: ./serverless
    
tasks:
  default:
    desc: List Tasks.
    cmd: task -l

  cluster-kind-deploy:
    desc: Create kubernetes cluster with Kind.
    cmds:
      - task: cluster-kind-undeploy
      - kind create cluster --config kind.yml
      - kubectl cluster-info --context kind-kubernetes-stack || exit 1
    preconditions:
      - sh: test -f kind.yml
        msg: Kind's manisfest not provided
  
  cluster-kind-undeploy:
    desc: Delete Kind kubernetes cluster.
    cmd: kind delete cluster --name kubernetes-stack
