version: 3

# Global Properties
silent: true

dotenv:
  - .env

includes:
  ingress:
    taskfile: ./ingress/tasks.yml
    dir: ./ingress
  gitops:
    taskfile: ./gitops/tasks.yml
    dir: ./gitops
  observability:
    taskfile: ./observability/tasks.yml
    dir: ./observability
  security:
    taskfile: ./security/tasks.yml
    dir: ./security
  control-plane:
    taskfile: ./control-plane/tasks.yml
    dir: ./control-plane
  serverless:
    taskfile: ./serverless/tasks.yml
    dir: ./serverless
  gateway:
    taskfile: ./gateway/tasks.yml
    dir: ./gateway

tasks:
  default:
    desc: List Tasks.
    cmd: task -l

  cluster-kind-deploy:
    desc: Create kubernetes cluster with Kind.
    cmds:
      - kind delete cluster --name kubernetes-stack || true
      - kind create cluster --config kind.yml
      - kubectl cluster-info --context kind-kubernetes-stack || exit 1
    preconditions:
      - sh: test -f kind.yml
        msg: Kind's manisfest not provided

  cluster-kind-undeploy:
    desc: Delete Kind kubernetes cluster.
    cmd: kind delete cluster --name kubernetes-stack

  pre-commit-install:
    desc: Install pre-commit
    cmd: pre-commit install

  platform-install:
    desc: Install all the components required for the kubernetes platform.
    deps:
      - task: ingress:nginx-install
      - task: gateway:nginx-install
      - task: security:cert-manager-install
    cmd: kubectl apply -f security/cert-manager/self.clusterissuer.yml

  devcontainer-prebuild:
    desc: Pre-Build DevContainer
    cmd: |
      devcontainer build \
        --workspace-folder ./ \
        --push false \
        --image-name ghcr.io/nzuguem/kubernetes-sandbox-environment:latest \
        --cache-from ghcr.io/nzuguem/kubernetes-sandbox-environment:latest
