version: 3

# Global Properties
silent: true

dotenv:
  - .env

includes:
  ingress:
    taskfile: ./ingress/tasks.yml
    dir: ./ingress
  gitops:
    taskfile: ./gitops/tasks.yml
    dir: ./gitops
  observability:
    taskfile: ./observability/tasks.yml
    dir: ./observability
  security:
    taskfile: ./security/tasks.yml
    dir: ./security
  control-plane:
    taskfile: ./control-plane/tasks.yml
    dir: ./control-plane
  serverless:
    taskfile: ./serverless/tasks.yml
    dir: ./serverless
  gateway:
    taskfile: ./gateway/tasks.yml
    dir: ./gateway

tasks:
  default:
    desc: List Tasks.
    cmd: task -l

  cluster-kind-deploy:
    desc: Create kubernetes cluster with Kind.
    cmds:
      - |-
        count=$(docker ps --filter "name=kubernetes-stack" -q | wc -l)
        if [ "$count" -ne 3 ]; then
          echo "🆕 Creation of the Kind cluster ..."
          kind create cluster --config kind.yml
        else
          echo "💚 Re-using the Kind cluster. Containers start up..."
          sleep 10s
        fi
      - kubectl cluster-info --context kind-kubernetes-stack || exit 1
    preconditions:
      - sh: test -f kind.yml
        msg: Kind's manisfest not provided

  cluster-kind-undeploy:
    desc: Delete Kind kubernetes cluster.
    cmd: kind delete cluster --name kubernetes-stack

  pre-commit-install:
    desc: Install pre-commit
    cmd: pre-commit install

  platform-install:
    desc: Install all the components required for the kubernetes platform.
    deps:
      - task: ingress:nginx-install
      - task: gateway:nginx-install
      - task: security:cert-manager-install
    cmd: kubectl apply -f security/cert-manager/self.clusterissuer.yml
