apiVersion: v1
kind: Service
metadata:
  name: pastry-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: pastry-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastry-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pastry-api
  template:
    metadata:
      labels:
        app: pastry-api
    spec:
      containers:
        - name: pastry-api
          image: quay.io/microcks/quarkus-api-pastry
          ports:
            - name: http
              containerPort: 8282