apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventing-hello-trigger-service-reply
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/nzuguem/cloudevents-handler