apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: eventing-hello-ping-source-broker
spec:
  schedule: "*/2 * * * *"
  data: '{"message": "Thanks for doing Knative Tutorial"}'
  sink:  
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default