---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    foo: AgBi5OyzvVMb7R8LIxFOVYzkCoyM/a4oEvgMDvzVQkluvo05a7LM0wOor4L9mgP5Xe+qE4jhVg99M9+8wP+o92VqAjt7+ydZEeVwaCkiYLCWdXkG+c5JWLAN3wzCL7JLJB1VYHLLil4XKoXtklZINCInladzp20dE1h6V4rv4T76CXE3FZh5NxWvzWGLLG+Zr9Z8MizdxLxjewi6BbRQDh1I07lavLgsLJEfNJIl1Me4Du5fVCkNGTFp5+ntBG5gSb9gIZnaGRLuROIxP9Yggsu60wlmiJmv/NNj7P60fNEEkdqK4MsNJcpmAJXief0X/DGYKGDEJmwBsP6CSVVexjVp96ipfCu5CyHrVd9Uv0b1ZTupVxQaK1B5+xWkjZPSPrfQ53TxAE6Lda+hZsA3jH2oOBodOA/BwV2J6PJ+3QscORJRz9eJGtwDF3rlXMDFVcA2ig0WxyHc1iawFlGrolE9sVycfbEgbvZw8g/ivD71UjuqoXJf0RxW4THj5A91aiw0wEExh0/abocB74EonHuu2YdUVdBJXMUXMAbkFIx2z+hS26Wtg3sK0+YLuKOKMPDYKW0mgFNPlVLRp2OOMt7N2ANiN2a7Od+0LbyuUtNjuQzmIR7MQ80JUvSWar2ZAQhYz1c0KMnb0U1/q8EmNXNXU0nnCainZ8H/FO+aoiy140guCGRdKR0BHrdPIfDpOIhKkhQ=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
