cassandra:
  config:
    cluster_size: 1

elasticsearch:
  replicas: 1

prometheus:
  enabled: true

grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana-temporal.127.0.0.1.nip.io

server:
  replicaCount: 1
  config:
    namespaces:
      create: true
  internalFrontend:
    enabled: true
  frontend:
    ingress:
      enabled: true
      className: nginx
      # Grpc Reguired TLS connection on Ingress-nginx
      # https://github.com/kubernetes/ingress-nginx/issues/3897
      tls:
      - secretName: temporal-gateway.127.0.0.1.nip.io-tls
        hosts:
        - temporal-gateway.127.0.0.1.nip.io
      hosts:
        - temporal-gateway.127.0.0.1.nip.io
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: GRPC # Enable support of HTTP/2, for GRPC Client
        nginx.org/grpc-services: temporal-frontend
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
web:
  ingress:
    enabled: true
    className: nginx
    hosts:
      - temporal-ui.127.0.0.1.nip.io
  additionalEnv:
  - name: TEMPORAL_OPENAPI_ENABLED
    value: "true"
  - name: TEMPORAL_SHOW_TEMPORAL_SYSTEM_NAMESPACE
    value: "true"
  - name: TEMPORAL_DISABLE_WRITE_ACTIONS
    value: "false"
  - name: TEMPORAL_WORKFLOW_TERMINATE_DISABLED
    value: "true"
  - name: TEMPORAL_WORKFLOW_CANCEL_DISABLED
    value: "true"
  - name: TEMPORAL_WORKFLOW_SIGNAL_DISABLED
    value: "false"
  - name: TEMPORAL_WORKFLOW_RESET_DISABLED
    value: "false"
  - name: TEMPORAL_BATCH_ACTIONS_DISABLED
    value: "true"
  - name: TEMPORAL_START_WORKFLOW_DISABLED
    value: "false"
  - name: TEMPORAL_AUTH_ENABLED
    value: "false"
  - name: TEMPORAL_CSRF_COOKIE_INSECURE
    value: "true"
