apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: crossplane-bucket-
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-west-3
  providerConfigRef:
    name: localstack