apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: eventing-hello-trigger-reply
spec:
  broker: default
  filter:
    attributes:
      type: me.nzuguem.cloudevents.example.reply
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventing-hello-trigger-service-reply