manager:
  ingress:
    enabled: true
    host: neuvector.127.0.0.1.nip.io
    ingressClassName: nginx
    path: /
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    tls: true
    secretName: neuvector.127.0.0.1.nip.io-tls