apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-daemonset
spec:
  # Automatic resource update in the event of an operator update
  upgradeStrategy: automatic
  serviceAccount: otelcontribcol
  mode: daemonset
  volumes:
  - name: varlogpods
    hostPath:
      path: /var/log/pods
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  volumeMounts:
  - name: varlogpods
    mountPath: /var/log/pods
    readOnly: true
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  config:
    receivers:
      receiver_creator:
        watch_observers: [k8s_observer]
        discovery:
          enabled: true
      filelog:
        include_file_path: true
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          # Exclude logs from all containers named otel-collector
          - /var/log/pods/*/otel-collector/*.log
          - /var/log/pods/*/otc-container/*.log
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    extensions:
      k8s_observer:
        auth_type: serviceAccount
        observe_pods: true
        observe_nodes: true
        observe_services: true
        observe_ingresses: true

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: lgtm.default.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      extensions: [k8s_observer]
      pipelines:
        logs:
          receivers: [filelog, receiver_creator]
          processors: []
          exporters: [debug, otlp]
