apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert-manager
spec:
  isCA: true
  renewBefore: 24h
  duration: 100h
  secretName: nginx-cert-manager.127.0.0.1.nip.io-tls # Secret to be created with TLS KeyPair
  commonName: nginx-cert-manager.127.0.0.1.nip.io
  dnsNames:
  - nginx-cert-manager.127.0.0.1.nip.io
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer