apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-config-es
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aws-config-secret
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: cloud/config/aws
      property: access_key_id
  - secretKey: AWS_ACCESS_SECRET_KEY
    remoteRef:
      key: cloud/config/aws
      property: access_secret_key
