apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kubernetes-sandbox-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "*.127.0.0.1.nip.io"
    allowedRoutes:
      namespaces:
        from: All
