# https://www.solo.io/blog/istio-ambient-argo-cd-kind-15-minutes
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd-system
spec:
  project: platform
  destination:
    namespace: istio-system
    name: in-cluster
  sources:
  - chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.30.2
    helm:
      values: |
        profile: ambient
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy
