apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd-system
spec:
  project: platform
  destination:
    namespace: kube-system
    name: in-cluster
  sources:
  - chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.2
    helm:
      valuesObject:
        args:
        # https://github.com/kubernetes-sigs/metrics-server/issues/1025
        # "tls: failed to verify certificate: x509: cannot validate certificate"
        - --kubelet-insecure-tls
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
