apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd-system
spec:
  project: platform
  destination:
    namespace: ingress-nginx-system
    name: in-cluster
  sources:
    - repoURL: https://github.com/nzuguem/kubernetes-sandbox-environment
      targetRevision: main
      ref: values
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.11.3
      helm:
        valueFiles:
        - $values/ingress/nginx/helm.values.yml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
