apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway
  namespace: argocd-system
spec:
  project: platform
  destination:
    namespace: nginx-gateway-system
    name: in-cluster
  sources:
  - repoURL: https://github.com/nginx/nginx-gateway-fabric
    targetRevision: v2.2.2
    path: config/crd/gateway-api/experimental
  - path: .
    repoURL: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
    targetRevision: 2.2.2
    helm:
      valueFiles:
      - $values/gateway/nginx/helm.values.yml
  - repoURL: https://github.com/nzuguem/kubernetes-sandbox-environment
    targetRevision: main
    ref: values
  - repoURL: https://github.com/nzuguem/kubernetes-sandbox-environment
    targetRevision: main
    path: gateway/nginx/gateways
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
