ingress_nginx:
  installed: true
  chart_version: 4.12.1
  secrets:
    aws:
      # accessKeyId: ref+vault://nzuguem/dev/helm/ingress-nginx/cloud/config/aws#access_key_id
      # secretAccessKey: ref+vault://nzuguem/dev/helm/ingress-nginx/cloud/config/aws#access_secret_key
      accessKeyId: foo
      secretAccessKey: bar
