apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-native-application-oci-manisfest
  namespace: argocd-system
spec:
  destination:
    namespace: spring-native-application
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: oci://registry-1.docker.io/nzuguem/oci-k8s-manifest-spring-native 
    targetRevision: latest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
