inferenceExtension:
  enabled: true
  autoProvision: true

nodeSelector:
    gateway-ready: "true"
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
    effect: "NoSchedule"
