name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/**
      - .github/.devcontainer/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU (for more platforms support)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      env:
        # https://github.com/devcontainers/ci/issues/191#issuecomment-1603857155
        BUILDX_NO_DEFAULT_ATTESTATIONS: true
      with:
        subFolder: .github
        platform: linux/amd64,linux/arm64
        imageName: ghcr.io/${{ github.repository }}
        cacheFrom: ghcr.io/${{ github.repository }}
        cacheTo: ghcr.io/${{ github.repository }}
        push: always
