apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager # Store of secrets created beforehand
    kind: ClusterSecretStore
  target:
    name: app-password # Secret Kubernetes to be created by ESO
  data:
  - secretKey: app-password # Arbitrary choice of Key Name
    remoteRef:
      key: my-eso-secret
      property: password