
# AWS credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: localstack-creds
type: Opaque
data:
  # This is just test/test.
  access-key: dGVzdA==
  secret-access-key: dGVzdA==

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-3
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-creds
            key: access-key
          secretAccessKeySecretRef:
            name: localstack-creds
            key: secret-access-key