apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: temporal-api-keys-gen
spec:
  refreshInterval: "5m0s"
  target:
    name: temporal-api-key
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Webhook
          name: temporal-api-keys-gen
